site_name: zsh-nvim Documentation
theme: "material"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: "#087da1"
    accent: "#00a889"
  font:
    text: "Source Sans Pro"

repo_name: "luismayta/zsh-nvim"
repo_url: "https://github.com/luismayta/zsh-nvim"
copyright: 'Copyright © 2020 <a href="https://.com"></a>'

google_analytics:
  - ""
  - "auto"
